import type { Workflow, WorkflowNode, WorkflowEdge } from '@/types/workflow';

const nodes: WorkflowNode[] = [
  {
    id: 'trigger',
    type: 'trigger',
    config: { trigger_type: 'manual' },
    position: { x: 250, y: 0 },
  },
  {
    id: 'sync',
    type: 'github.sync',
    config: {
      owner: '{{config.owner}}',
      repo: '{{config.repo}}',
      path: '{{config.workspace_path}}',
    },
    position: { x: 250, y: 100 },
  },
  {
    id: 'readIssues',
    type: 'github.readIssues',
    config: {
      owner: '{{sync.owner}}',
      repo: '{{sync.repo}}',
    },
    position: { x: 250, y: 200 },
  },
  {
    id: 'hasIssues',
    type: 'condition',
    config: {
      condition: '{{readIssues.count}}',
      operator: 'gt',
      value: 0,
    },
    position: { x: 250, y: 300 },
  },
  {
    id: 'plan',
    type: 'claude.plan',
    config: {
      prompt: 'Analyze this GitHub issue and create a detailed implementation plan:\n\nTitle: {{readIssues.issues.0.title}}\nBody: {{readIssues.issues.0.body}}\n\nProvide a step-by-step plan to resolve this issue.',
    },
    position: { x: 250, y: 400 },
  },
  {
    id: 'worktree',
    type: 'git.worktree',
    config: {
      worktree_path: '{{sync.repo_path}}-worktree',
      branch_name: 'feature/issue-{{readIssues.issues.0.number}}',
    },
    position: { x: 250, y: 500 },
  },
  {
    id: 'apply',
    type: 'claude.apply',
    config: {
      prompt: 'Implement the following plan to resolve the issue:\n\n{{plan.plan}}\n\nMake the necessary code changes.',
    },
    position: { x: 250, y: 600 },
  },
  {
    id: 'commit',
    type: 'git.commit',
    config: {
      commit_type: 'feat',
      scope: 'issue-{{readIssues.issues.0.number}}',
      description: '{{readIssues.issues.0.title}}',
    },
    position: { x: 250, y: 700 },
  },
  {
    id: 'createPR',
    type: 'github.createPR',
    config: {
      owner: '{{sync.owner}}',
      repo: '{{sync.repo}}',
      title: '{{readIssues.issues.0.title}}',
      body: 'Resolves #{{readIssues.issues.0.number}}\n\n## Plan\n{{plan.plan}}\n\n## Changes\nAutonomously generated by Autonomous Agent.',
      head: 'feature/issue-{{readIssues.issues.0.number}}',
      base: 'develop',
    },
    position: { x: 250, y: 800 },
  },
];

const edges: WorkflowEdge[] = [
  { id: 'e1', source: 'trigger', target: 'sync' },
  { id: 'e2', source: 'sync', target: 'readIssues' },
  { id: 'e3', source: 'readIssues', target: 'hasIssues' },
  {
    id: 'e4',
    source: 'hasIssues',
    target: 'plan',
    sourceHandle: 'true',
  },
  { id: 'e5', source: 'plan', target: 'worktree' },
  { id: 'e6', source: 'worktree', target: 'apply' },
  { id: 'e7', source: 'apply', target: 'commit' },
  { id: 'e8', source: 'commit', target: 'createPR' },
];

export function createAutonomousDeveloperWorkflow(config: {
  owner: string;
  repo: string;
  workspacePath: string;
}): Omit<Workflow, 'id' | 'createdAt' | 'updatedAt' | 'version'> {
  return {
    name: 'Autonomous Developer',
    description:
      'Full autonomous workflow: sync repo, read issues, plan with Claude, create worktree, apply changes, commit, and create PR.',
    nodes,
    edges,
    config: {
      owner: config.owner,
      repo: config.repo,
      workspace_path: config.workspacePath,
    },
  };
}
